connection_string='postgres://koyeb-adm:NqB4a9ESiYnP@ep-floral-haze-a4l7sdfx.us-east-1.pg.koyeb.app/koyebdb'


databaseSuperUser_server='localhost'

databaseport='5432'
databaseuser = 'postgres'
database_password='30794009'
db_name='recommendationsSystems'

