connection_string='your_connection_string'


#legado - não usa mais, porém se tirar quebra.
databaseSuperUser_server='yourhost'
databaseport='your_port'
databaseuser = 'your_user'
database_password='your_password'
db_name='your_db_name'

